export default [{
    key: '1',
    name: 'After Dark',
    author: 'Murakami',
    reviews: 2,
    rating: 4.2,
    raters: 45,
},{
    key: '2',
    name: 'After Dark',
    author: 'Murakami',
    reviews: 2,
    rating: 4.2,
    raters: 45,
},{
    key: '3',
    name: 'After Dark',
    author: 'Murakami',
    reviews: 2,
    rating: 4.2,
    raters: 45,
},{
    key: '4',
    name: 'After Dark',
    author: 'Murakami',
    reviews: 2,
    rating: 4.2,
    raters: 45,
},{
    key: '5',
    name: 'After Dark',
    author: 'Murakami',
    reviews: 2,
    rating: 4.2,
    raters: 45,
},{
    key: '6',
    name: 'After Dark',
    author: 'Murakami',
    reviews: 2,
    rating: 4.2,
    raters: 45,
},{
    key: '7',
    name: 'After Dark',
    author: 'Murakami',
    reviews: 2,
    rating: 4.2,
    raters: 45,
},{
    key: '8',
    name: 'After Dark',
    author: 'Murakami',
    reviews: 2,
    rating: 4.2,
    raters: 45,
},]